<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Y.Results.Extensions.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Y.Results.Classes.Extensions\Y.Results.Classes.Extensions.csproj" />
    <ProjectReference Include="..\Y.Results.Classes\Y.Results.Classes.csproj" />
  </ItemGroup>

</Project>
