<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Y.Results</RootNamespace>
        <DefineConstants>$(DefineConstants);STRUCTS</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <Compile Include="..\Y.Results.Classes\Result.cs">
        <Link>Result.cs</Link>
      </Compile>
      <Compile Include="..\Y.Results.Classes\Result.Ctors.cs">
        <Link>Result.Ctors.cs</Link>
      </Compile>
      <Compile Include="..\Y.Results.Classes\Result.Generic.cs">
        <Link>Result.Generic.cs</Link>
      </Compile>
      <Compile Include="..\Y.Results.Classes\Result.Wrap.cs">
        <Link>Result.Wrap.cs</Link>
      </Compile>
    </ItemGroup>

</Project>
