<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Y.Results</RootNamespace>
        <DefineConstants>$(DefineConstants);STRUCTS</DefineConstants>
    </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>$(AssemblyName).Extensions</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

    <ItemGroup>
      <Compile Include="..\Y.Results.Classes\Result.cs">
        <Link>Result.cs</Link>
      </Compile>
      <Compile Include="..\Y.Results.Classes\Result.Ctors.cs">
        <Link>Result.Ctors.cs</Link>
      </Compile>
      <Compile Include="..\Y.Results.Classes\Result.Generic.cs">
        <Link>Result.Generic.cs</Link>
      </Compile>
      <Compile Include="..\Y.Results.Classes\Result.Wrap.cs">
        <Link>Result.Wrap.cs</Link>
      </Compile>
      <Compile Include="..\Y.Results.Classes\Result.Methods.cs">
        <Link>Result.Methods.cs</Link>
      </Compile>
      <Compile Include="..\Y.Results.Classes\Result.WhenAll.cs">
        <Link>Result.WhenAll.cs</Link>
      </Compile>
    </ItemGroup>

</Project>
