<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Y.Results</RootNamespace>
    <DefineConstants>$(DefineConstants);CLASSES</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>$(AssemblyName).Extensions</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  
  <ItemGroup>
    <Compile Remove="Result.Equatable.cs" />
  </ItemGroup>

</Project>
